prepare:
  fetch:
    - url: "https://raw.githubusercontent.com/Freshly/spicerack/master/spicerack-styleguide/rubocop.yml"
      path: ".rubocop.yml"

plugins:
  rubocop:
    enabled: true

exclude_patterns:
  - "**/bin/"
  - "**.gemspec"

ratings:
  paths:
    - "**.rb"
