name: RSpec

on: push

jobs:
  build_rails_5_2:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ "2.5.x", "2.6.x" ]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libsqlite3-dev
        sudo apt-get install redis-server
        gem install bundler
        echo "gem 'activesupport', '~> 5.2.0'" >> Gemfile
        echo "gem 'activerecord', '~> 5.2.0'" >> Gemfile
        echo "gem 'railties', '~> 5.2.0'" >> Gemfile
        bundle update activesupport activerecord railties
        bundle install --jobs 4 --retry 3
    - name: Run RSpec
      run: |
        bundle exec rspec

  build_rails_6_0:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ "2.5.x", "2.6.x" ]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libsqlite3-dev
        sudo apt-get install redis-server
        gem install bundler
        echo "gem 'activesupport', '~> 6.0.0'" >> Gemfile
        echo "gem 'activerecord', '~> 6.0.0'" >> Gemfile
        echo "gem 'railties', '~> 6.0.0'" >> Gemfile
        bundle update activesupport activerecord railties
        bundle install --jobs 4 --retry 3
    - name: Run RSpec
      run: |
        bundle exec rspec
