name: RSpec

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - "2.5.x"
          - "2.6.x"
          - "2.7.x"
        rails:
          - "5.2.0"
          - "6.0.0"
          - "6.1.0"

    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ matrix.ruby }}-${{ matrix.rails }}-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-${{ matrix.ruby }}-${{ matrix.rails }}
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Apply Rails ${{ matrix.rails }} dependencies
      run: |
        echo "gem 'activesupport', '~> ${{ matrix.rails }}'" >> Gemfile
        echo "gem 'activerecord', '~> ${{ matrix.rails }}'" >> Gemfile
    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libsqlite3-dev
        sudo apt-get install redis-server
        gem install bundler
        bundle config path vendor/bundle
        bundle update activesupport activerecord
        bundle install --jobs 4 --retry 3
    - name: Run RSpec
      run: |
        bundle exec rspec
