name: RSpec

on: [push]

dependencies: &dependencies
- name: Set up dependencies
  run: |
    sudo apt-get install libsqlite3-dev
    sudo apt-get install redis-server
    gem install bundler
    bundle install --jobs 4 --retry 3

rspec: &rspec
- name: Run RSpec
  run: |
    bundle exec rspec

jobs:
  ruby_2_5:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.5
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5.x
    - *dependencies
    - *rspec


  ruby_2_6:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - *dependencies
    - *rspec
